In [1]:
import pandas as pd
import nltk
import re
from nltk import pos_tag
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer

english_stopwords = set(stopwords.words('english'))

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     /Users/upanshuparekh/nltk_data...

True

# Data Preprocessing -- Reddit
In this part (2), I will be using [NLTK](https://www.nltk.org)'s data preprocessing functions to clean up the data produced by the `data_collection.py` script. This data must then be somehow plugged into sentiment analysis libraries to get some score.

Here's what I'll do. For each post:
- Get a sentiment score for the post title + self text, call it $s_0$
- Get a sentiment score for each top comment, call them $s_1, s_2, ..., s_{10}$
- Get a weighted aggregate sentiment score for the post. Weighing a score $s_i$ less as $i$ increases. I will just begin with the simple function: $w(s_i) = 1/i$ to multiply to a score to weigh it.

For each month's of post sentiment scores, I will take the median score as the representation for the entire month, as this statistic is more resistant to outliers.

I have to do it like this because sentiment analysis really starts to break when the text gets too long, either with NLTK's VADER, or with FinBERT. You will see this in my previous commits if you want to look.

So all the data preprocessing will preserve the fields necessary to conduct this analysis.

In [2]:
df = pd.concat([
    pd.read_csv('reddit-cryptocurrency-data.csv'),
    pd.read_csv('reddit-wallstreetbets-data.csv'),
    pd.read_csv('reddit-finance-data.csv'),
    pd.read_csv('reddit-investing-data.csv'),
], ignore_index=True)

In [3]:
df.columns

Index(['subreddit', 'month', 'post_id', 'post_title', 'post_selftext', 'tc0',
       'tc1', 'tc2', 'tc3', 'tc4', 'tc5', 'tc6', 'tc7', 'tc8', 'tc9'],
      dtype='object')

In [5]:
df.sample(5)

,subreddit,month,post_id,post_title,post_selftext,tc0,tc1,tc2,tc3,tc4,tc5,tc6,tc7,tc8,tc9
2979,finance,Jun,1d5qr5w,Investing concept - Margin of safety,[removed],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3510,finance,Dec,1hk8o0t,Elizabeth Warren urges regulators to block Cap...,NaN,"In other news, water is wet, and Tuesday follo...",she is way off base—-this merger is about cred...,This is exactly it. Congress complains that V...,because Cap One is a large issuer of cards but...,wonder how much Visa is paying her for these c...,Says the woman who made 600k for teaching a cl...,How exactly does that justify a corporate merger?,If I recall market share is something like V...,By having enough market share to realistically...,If Capital One was a medical device manufactur...
2005,wallstreetbets,Sep,1frrah6,"Boys, we’re cooked….",NaN,Well for the first time in a long time that gr...,New level unlocked: sucked off under water.,https://preview.redd.it/qarsqg2f4nrd1.jpeg?wid...,Waffle House next door is still open.,Holy shit lol,"dumpster's still there, wdym?",https://preview.redd.it/9iuafb893nrd1.jpeg?wid...,New response dropped,![img](emote|t5_2th52|4271),Komrade!!! It is .... Free housing Free wa...
1706,wallstreetbets,Jun,1de838p,So....this is my first time trading options an...,NaN,Just wait until you *lose* 100k in an hour.,Latest update: I just made $99k. I'm done now...,Congrats fam. Pullout game strong. Now even i...,Congrats on the freebee Take it and RUN else...,post your original trade you muppet. how much ...,This is far too reasonable for this sub. But y...,1st submission with an 8 year account... 100k ...,Stick it in spy or voo and forget about it,The first ones free. But seriously cash out a...,First ones free? Shit. I received a colonoscop...
4333,investing,Aug,1euw1q6,What is everyone’s plan when rates move lower?,"Lots of talk about HYSA’s, short term treasuri...",stay the course,6 month emergency savings. Dumping everything ...,Your cash allocation should be your cash alloc...,I feel like this is said every year by numerou...,HYSA’s will always be a better option than tra...,"This is r/investing, not r/bogleheads. We are ...","Granny, is that you?",What needs to be liquid (emergency fund) will ...,Never done coke either. Just felt like cocaine...,I would disagree on that. Why have a cash allo...

In [4]:
# Combine `post_title`, `post_selftext` into a column 'headline'
cols_to_combine = ['post_title', 'post_selftext']
df['headline'] = df[cols_to_combine].fillna('').agg(' '.join, axis=1)
df = df.drop(columns=cols_to_combine)

In [5]:
df.sample(5)

,subreddit,month,post_id,tc0,tc1,tc2,tc3,tc4,tc5,tc6,tc7,tc8,tc9,headline
3325,finance,Oct,1g28oau,Or a blind trust to let them take advantage of...,An easy fix would just be to limiting them to ...,Guaranteed to not happen if it is Dem house an...,"Neither party will support it, it’s virtue sig...",Not in favor of banning them from trading or o...,Yep,This is overmentioned. If its voted through it...,NaN,NaN,NaN,Thoughts on Bipartisan bill to remove lawmaker...
677,cryptocurrency,Jul,1dw1c52,German government out here selling their holdi...,and with bureaucracies that's probably exactly...,A new challenger emerges to try and stop the g...,"yeah, seen yesterday's chart on that, the dude...","I also made an offer, but they didn't accept it.",tldr; Tron founder Justin Sun has offered to b...,"Steady lads, deploying more capital",Fuck this guy,yeah this whole Germany thing is a mystery. No...,Movie2k pirate streaming website founders,Justin Sun Offers to Buy Germany's BTC
59,cryptocurrency,Jan,19baj6k,Then how do I become an insider and set up my ...,Why the comedy tag? This is 100% pure fact of ...,First thing...are you good at lying?,dogecoiners say hi,Also you need a group of desperate friends who...,"Ahh, there is always a catch -.-",This post is about me and I don't like it.,Don’t,We need friends for this?,Safemoon enters the chat,Who wants to be a millionaire! You? In order t...
1439,wallstreetbets,Mar,1bdet8k,So is 78% of population here Indian?,1 billion regards,Ya /wallstreetbets should be renamed /gullyboy...,"""this loss was equivalent to 110,000 rupees wh...",![img](emote|t5_2th52|4276) how do we convince...,Dalalstreetbets,Lol. I met a dude from India here in Canada in...,Inverse India instead of Cramer,"Simple, say that Ambani invested in Intel and ...",Let’s get a discord going with all of them,India accounted for 78% of all options in 2023...
4098,investing,May,1cyz5bs,That’s not a 401k if everyone’s contributions ...,This guy's almost definitely in a cash balance...,That’s weird. Definitely need more information.,Are the gains only based on the prior balance?...,Are you sure it’s actually invested and not ju...,"I got this email ""Fake Company 401k is a ...",https://www.efast.dol.gov/5500Search/?_ga=2.63...,Being very selective and not thinking about dc...,&gt;but $400 after 3 years is significantly un...,"This is perfect, thank you!!",Employer 401k Seems Fishy [deleted]

## Text Cleaning Function
I did research the tradeoff between stemming vs. lemmatizing, and in general I got that:
- Stemming = rules-based, heuristic algorithmic removal of common word endings
    - faster for larger datasets, loses accuracy and context, can produced nonexistent words
- Lemmatizing = more accurate, more computationally expensive with Part-of-Speech Tagging required

But I reason that I'm not training an ML model where accuracy is mission critical, so simply
stemming should suffice.

In [8]:
def clean_text_stemmer(text: str) -> str:
    """
    Clean the input text by removing URLs, special characters, and extra whitespace, and using
    NLTK's tokenization, stopword removal, stemming.
    """
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove special characters and digits, keep important punctuation
    text = re.sub(r'[^A-Za-z\s.,!?]', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip().lower()

    words = word_tokenize(text)
    # Remove stopwords
    words = [word for word in words if word not in english_stopwords]
    # Stemming
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    text = ' '.join(words)
    return text + '.'

In [9]:
# example_text = df['text'].iloc[2226]
# example_text

In [10]:
example_text_stemmed = clean_text_stemmer(example_text)
example_text_stemmed

'dow soar , point record , russel jump trump defeat harri.'

Okay, maybe lemmatizing is the better strategy, there are just too many nonsense words here that can throw off the sentiment analyzer.

In [6]:
def clean_text_lemmatizer(text: str) -> str:
    """
    Clean the input text by removing URLs, special characters, and extra whitespace, and using
    NLTK's tokenization, stopword removal, lemmatizer.
    """
    # POS tagging for lemmatization
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    pos_tags = pos_tag(word_tokenize(text))
    lemmatizer = WordNetLemmatizer()
    # Map POS tags to WordNet format
    tag_dict = {
        "J": wordnet.ADJ,  # Adjective
        "N": wordnet.NOUN, # Noun
        "V": wordnet.VERB, # Verb
        "R": wordnet.ADV   # Adverb
    }
    pos_tags = [(word, tag_dict.get(tag[0], 'n')) for word, tag in pos_tags]

    # Lemmatization
    words = [lemmatizer.lemmatize(word, pos).lower() for word, pos in pos_tags]
    # Remove stopwords
    words = [word for word in words if word not in english_stopwords]
    text = ' '.join(words)

    # Remove special characters and digits, keep important punctuation
    text = re.sub(r'[^A-Za-z\s.,!?]', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip().lower()

    return text + '.'  # For FinBERT

In [12]:
example_text

'Dow soars 1,300 points to a record, Russell 2000 jumps 4% as Trump defeats Harris '

In [13]:
example_text_lemmatized = clean_text_lemmatizer(example_text)
print('LEMMATIZED: ' + example_text_lemmatized)
print('STEMMED: ' + example_text_stemmed)

LEMMATIZED: dow soar , point record , russell jump trump defeat harris.
STEMMED: dow soar , point record , russel jump trump defeat harri.

## Applying Lemmatizer to Whole Text Column
Okay the lemmatizer **definitely works a lot better**, it's a whole lot more accurate in its processing. Gonna stick with that! Now to apply it to the whole text column.

In [7]:
# For some reason there are floats in the text data, have to replace those with empty string
cols = ['headline'] + [f'tc{i}' for i in range(10)]
df[cols] = df[cols].astype(str)

In [53]:
for col in cols:
    df[col] = df[col].apply(clean_text_lemmatizer)

In [54]:
df.sample(4)

,subreddit,month,post_id,tc0,tc1,tc2,tc3,tc4,tc5,tc6,tc7,tc8,tc9,headline
4516,investing,Oct,1fu1qjr,low go ? hysa practically zero decade . statis...,. keep enough cash cash hysa emergency month g...,japan negative nominal interest rate decade bo...,"invest general recommendation , lose . , world...",view hysa investment tool . . place safely sto...,good lesson recency bias ..,"get boat op , invest instead put away account ...","sofi still . , think spaxx ..",case nt consider . inflation around right want...,react . hysa rate fall vacuum . low risk optio...,"react fall hysa interest rate ? week get pay ,..."
234,cryptocurrency,Mar,1bc9lsq,hope theoretical dip happen nontheoretical mon...,m curious see etfs cushion drop somewhat peopl...,"hate say time s different s lie , love say , m...",cash ready . working hour take overtime much p...,according every crypto influencer yt s hour le...,"er , re call dip , re call buying opportunitie...","time definitely feels different , least regard...","s theory bitcoin bull cycle cause halvings , r...","yea , price go ath month halving crazy . alone...",lol.yes samesie ..,ready big dip even bull market . s unusual see...
2998,finance,Jun,1d9pvxw,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,afford ? remove.
804,cryptocurrency,Sep,1fi1wne,show btc.,one go check headline claim ... year ago today...,remember bullish it immediately think send eth...,benjamin cowen enter chat .....,"alt like , since last bull run.",one ? nt bullrun since.,bitcoin go k dec k march . call bull run ?.,moment talk bitcoin dominance ?.,"thanks , make sense ..",make sense make clear ..,"year ago today , eth officially complete longa..."

In [55]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv('reddit-cleaned.csv', index=False)