In [27]:
import pandas as pd

# Sentiment Models Comparisons -- Reddit
In this part (3), I'll be comparing the VADER pretrained model from NLTK's presets, and the FinBERT model from the PyTorch library.

The idea is that using a sentiment analysis model trained on financial data will allow it to pick up financial terms and keywords from the corpora better than the general purpose NLTK pretrained sentiment model.

I'm not sure exactly yet how I'll measure this effect, but for each model's results, I'll make a plot of sentiment results for each month of 2024. Then I'll decide from there.

## Data Treatment
The cleaned data consists of lemmatized top comments, and the "headline" column which has the post title + self text

Here's what I'll do. For each post:
- Get a sentiment score for the post title + self text (headline), call it $s_0$
- Get a sentiment score for each top comment, call them $s_1, s_2, ..., s_{10}$
- Get a weighted aggregate sentiment score for the post. Weighing a score $s_i$ less as $i$ increases. I will just begin with the simple function: $w(s_i) = \frac{1}{100} * (i - 10)^2 + 0.01$ to multiply to a score to weigh it. The $0.01$ is to just avoid weighing the last element at 0.

For each month, I will take the median score of the post scores of that month as the representation for the entire month, as this statistic is more resistant to outliers.

I have to do it like this because sentiment analysis really starts to break when the text gets too long, either with NLTK's VADER, or with FinBERT. You will see this in my previous commits if you want to look, but essentially I tried to combine all the info associated with each post into one supertext of the post, and tried to run an analysis ont that, but the models failed spectacularly with incredibly large bodies of text like that.

In [28]:
df = pd.read_csv('reddit-cleaned.csv')

In [29]:
df.sample(3)

,subreddit,month,post_id,tc0,tc1,tc2,tc3,tc4,tc5,tc6,tc7,tc8,tc9,headline
3284,finance,Sep,1f7imlh,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,wealthtech startup propelle prepares late sept...
3062,finance,Jul,1dtzz68,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,nan.,us fdic issue consent order thread bank fdic i...
1595,wallstreetbets,Apr,1c5fhn6,brain drugs reddit ..,nothing get adrenaline run like dte powell hour.,nasdaq speech ! img emotetth.,looks like crayon menu breakfast morning ..,great production value would recommend.,gona say ai nt ....,trade sideways ! img emotetth.,good video.,m chew crayon bet money ... m money.,question ?.,buckle regard.

In [30]:
df.drop(columns=['post_id'], inplace=True)

In [31]:
df.sample(3)

,subreddit,month,tc0,tc1,tc2,tc3,tc4,tc5,tc6,tc7,tc8,tc9,headline
2090,wallstreetbets,Sep,see even regard nt know screen shot make profit.,next time use crayon paper.,! img emotetth s fry sir.,.,"extra buck , ll swallow . see wendy s dumpster...",hell break next week ..,good send meal.,s literally guess s guy get lucky flip head ti...,damn meanwhile another week congrats regard sh...,? like know ?.,biggie fry medium frosty ! starting midaugust ...
2369,wallstreetbets,Dec,m go start x leverage fund base around company...,genius . start company leverage buy shitty com...,! ! ? ? ai ? ? ? m.,accept credit card.,"worry , company call quantom ai enhance drone ...",dream within dream.,.,another layer mstr ponzi scheme huh ? ?.,m.,.,go make company build entirely around take lev...
1015,cryptocurrency,Nov,microstrategy stock go explode ever get offici...,better title random crypto website make story ..,actually pull ... fair play ..,saylormoon change name saylormars happen.,sound like window dressing . keep bitcoin alre...,bullish nt know ! !.,m old enough remember crypto supposedly sort t...,m bitcoin eoy.,wait want create position administration . cry...,saylor rich man ever ..,donald trump cryptocurrency advisory council e...

In [32]:
subreddits = df['subreddit'].unique()
print(subreddits)

months = df['month'].unique()
print(months)

['cryptocurrency' 'wallstreetbets' 'finance' 'investing']
['Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Nov' 'Dec']

In [33]:
# Average character length of the text in the combined dataframe
cols = ['headline'] + [f'tc{i}' for i in range(10)]
for col in cols:
    avg_length = df[col].str.len().mean()
    print(f"Average character length of '{col}': {avg_length}")

Average character length of 'headline': 265.48604166666667
Average character length of 'tc0': 93.634375
Average character length of 'tc1': 93.5925
Average character length of 'tc2': 90.2875
Average character length of 'tc3': 86.71604166666667
Average character length of 'tc4': 89.99791666666667
Average character length of 'tc5': 86.103125
Average character length of 'tc6': 82.00625
Average character length of 'tc7': 82.99208333333333
Average character length of 'tc8': 84.21208333333334
Average character length of 'tc9': 81.914375

In [34]:
# Some columns are not of the correct data type
df[cols] = df[cols].astype(str)

Okay these are all reasonable character lengths, so I think the sentiment analyses should be much nicer compared to my previous attempt.

## NLTK Sentiment Analysis
In this section I'll use NLTK's sentiment analysis to convert all the columns into sentiment scores.

In [35]:
sample_headline = df['headline'].sample(1).values[0]
print(sample_headline)

fed hold rate steady , indicate one cut come year.

In [36]:
from nltk.sentiment import SentimentIntensityAnalyzer

In [37]:
sia = SentimentIntensityAnalyzer()

In [38]:
sia.polarity_scores(sample_headline)

{'neg': 0.208, 'neu': 0.792, 'pos': 0.0, 'compound': -0.2732}

### Compound Scores
So this mechanism divides it's output into a negative, neutral, positive, and compound score.
I'll just use compound for now, and see what the scores are.

In [39]:
# Apply the sentiment analysis and create new columns for each score
for col in cols:
    df[f'nltk_{col}'] = df[col].apply(lambda x: pd.Series(sia.polarity_scores(x)['compound']))

In [40]:
nltk_cols = ['nltk_' + col for col in cols]
df[nltk_cols].describe()

,nltk_headline,nltk_tc0,nltk_tc1,nltk_tc2,nltk_tc3,nltk_tc4,nltk_tc5,nltk_tc6,nltk_tc7,nltk_tc8,nltk_tc9
count,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000
mean,0.199883,0.105122,0.117957,0.116712,0.119415,0.118421,0.112893,0.111904,0.111550,0.118539,0.106968
std,0.511562,0.427102,0.426941,0.422013,0.408935,0.410454,0.411012,0.406843,0.410941,0.408678,0.405155
min,-0.988300,-0.984000,-0.999200,-0.976000,-0.987600,-0.989000,-0.992000,-0.965100,-0.972800,-0.978300,-0.985600
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.025800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.641600,0.421500,0.437775,0.421500,0.421500,0.421500,0.421500,0.401900,0.401900,0.401900,0.381800
max,0.999900,0.998300,0.996100,0.990200,0.997900,0.998300,0.996700,0.999400,0.995900,0.996500,0.993600

Okay so it seems that a majority of scores are slightly positive. But this is across the columns. Perhaps after I run my special weighted mean on each post and then take the median grouped by month, I'll see a different story.

In [51]:
def weighted_mean(row: pd.Series, cols: list[str]) -> float:
    def w(i: int) -> float:
        return 2.718281828459045 ** (-3 * i / len(cols))

    return sum([row[col] * w(i) for i, col in enumerate(cols)])

In [42]:
df['nltk_mu'] = df.apply(lambda row: weighted_mean(row, nltk_cols), axis=1)
nltk_month_avg = df.groupby('month', sort=False)['nltk_mu'].mean()

In [43]:
nltk_month_avg

month
Jan    0.613024
Feb    0.582073
Mar    0.475488
Apr    0.490010
May    0.607685
Jun    0.533945
Jul    0.519426
Aug    0.435420
Sep    0.470879
Oct    0.500421
Nov    0.573903
Dec    0.486802
Name: nltk_mu, dtype: float64

Hmm, still all positive! Note that this isn't a horrible thing, I shouldn't shape the results to my expectation. Looking at the actual S&P 500 graph:
![S&P 500 Graph 2024](S&P_500_2024.png)

Can see that there was a dip in March and July/August of that year, which does correspond to dips in sentiment scores around that time in the data, despite being positive, so perhaps there's something there! Let's standardize to see in detail.

In [44]:
nltk_month_avgs_standardized = (nltk_month_avg - nltk_month_avg.mean()) / nltk_month_avg.std()
nltk_month_avgs_standardized

month
Jan    1.532864
Feb    0.999400
Mar   -0.837690
Apr   -0.587399
May    1.440830
Jun    0.169872
Jul   -0.080389
Aug   -1.528301
Sep   -0.917136
Oct   -0.407941
Nov    0.858576
Dec   -0.642686
Name: nltk_mu, dtype: float64

Honestly pretty good! If we think out a monthly score of 0 representing a neutral attitude, a negative score seems to correlate to a bearish outlook versus a positive score being a bullish outlook in the short term.

## FinBERT Sentiment Analysis
Let's see how FinBERT does, given that it is specially trained on financial texts and sources.

In [45]:
from transformers import pipeline

finance_sentiment = pipeline("text-classification", model="ProsusAI/finbert")

Device set to use mps:0

In [46]:
finance_sentiment([sample_headline, sample_headline])

[{'label': 'neutral', 'score': 0.7249507308006287},
 {'label': 'neutral', 'score': 0.7249507308006287}]

In [47]:
from nltk import word_tokenize
from tqdm import tqdm

# Trim length of all entries to 256 tokens
# BERT tokens are defined differently to NLTK tokens, so I ran into issues with only accepting
# 512 tokens. I decided to use 256 tokens instead to avoid this issue.
def trim(text: str) -> str:
    tokens = word_tokenize(text)
    text = ' '.join(tokens[:256])
    return text

for col in tqdm(cols):
    df[col] = df[col].apply(trim)

100%|██████████| 11/11 [00:04<00:00,  2.68it/s]

In [49]:
# Batch processing because we are interfacing with an ML model, faster than processing one by one
for col in tqdm(cols):
    df[f'finbert_{col}'] = [result['score'] for result in finance_sentiment(df[col].tolist())]

100%|██████████| 11/11 [08:54<00:00, 48.61s/it]

In [50]:
finbert_cols = ['finbert_' + col for col in cols]
df[finbert_cols].describe()

,finbert_headline,finbert_tc0,finbert_tc1,finbert_tc2,finbert_tc3,finbert_tc4,finbert_tc5,finbert_tc6,finbert_tc7,finbert_tc8,finbert_tc9
count,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000
mean,0.827652,0.840486,0.841999,0.843407,0.846667,0.847204,0.849089,0.846862,0.850749,0.848561,0.850230
std,0.121613,0.114182,0.113813,0.113320,0.110894,0.110089,0.108245,0.109506,0.105396,0.111120,0.108110
min,0.338653,0.357835,0.378634,0.340005,0.358575,0.339309,0.378251,0.377495,0.410106,0.350109,0.367069
25%,0.778857,0.805715,0.809498,0.809498,0.813585,0.813965,0.817239,0.809926,0.816929,0.816750,0.817025
50%,0.877085,0.889690,0.891774,0.894129,0.895558,0.896674,0.897055,0.895425,0.897055,0.897239,0.898411
75%,0.915019,0.922356,0.922356,0.922356,0.922356,0.922356,0.922356,0.922356,0.922356,0.922356,0.922356
max,0.970994,0.971445,0.969743,0.964252,0.964797,0.971162,0.970081,0.967670,0.964342,0.969598,0.964005

In [59]:
df['finbert_mu'] = df.apply(lambda row: weighted_mean(row, finbert_cols), axis=1)
fb_month_avg = df.groupby(['month', 'subreddit'], sort=False)['finbert_mu'].mean().unstack()

In [60]:
fb_month_avg

subreddit  cryptocurrency  wallstreetbets   finance  investing
month
Jan              3.299042        3.323605  3.516767   3.296796
Feb              3.283458        3.341638  3.482349   3.324042
Mar              3.240270        3.304101  3.481946   3.267339
Apr              3.279065        3.321391  3.484113   3.339289
May              3.315136        3.281695  3.474452   3.332394
Jun              3.235935        3.318961  3.422391   3.272295
Jul              3.306568        3.275761  3.499937   3.357749
Aug              3.257794        3.278061  3.428155   3.339829
Sep              3.253614        3.298023  3.459436   3.355282
Oct              3.276306        3.301842  3.471460   3.341423
Nov              3.273651        3.324033  3.499773   3.305647
Dec              3.349126        3.282391  3.448873   3.290384

It seems that all the scores still are quite high, but the subtle patterns are there that correlate to March and July/August dips. Maybe standardizing could be helpful to see the dips.

In [61]:
fb_month_avgs_standardized = (fb_month_avg - fb_month_avg.mean(axis=0)) / fb_month_avg.std(axis=0)

In [62]:
pd.concat([nltk_month_avgs_standardized, fb_month_avgs_standardized], axis=1, keys=['nltk', 'finbert'])

           nltk        finbert
        nltk_mu cryptocurrency wallstreetbets   finance investing
month
Jan    1.532864       0.554872       0.888051  1.549594 -0.696857
Feb    0.999400       0.080057       1.717224  0.345544  0.176379
Mar   -0.837690      -1.235802      -0.008774  0.331475 -1.640947
Apr   -0.587399      -0.053804       0.786250  0.407277  0.665025
May    1.440830       1.045239      -1.039041  0.069309  0.444047
Jun    0.169872      -1.367874       0.674518 -1.751938 -1.482118
Jul   -0.080389       0.784183      -1.311870  0.960840  1.256667
Aug   -1.528301      -0.701871      -1.206130 -1.550300  0.682344
Sep   -0.917136      -0.829249      -0.288258 -0.456000  1.177610
Oct   -0.407941      -0.137851      -0.112645 -0.035363  0.733409
Nov    0.858576      -0.218748       0.907729  0.955088 -0.413187
Dec   -0.642686       2.080848      -1.007053 -0.825526 -0.902373

![S&P500 2024 Graph](S&P_500_2024.png)
Little better, it seems that FinBERT follows similar trends to NLTK, but FinBERT's June is way too pessimistic, and FinBERT's July is way too optimistic. Based on the actual S&P500 graph, it seems that NLTK actually performed better, so I will be using NLTK for my plotting and analysis moving forward.

In [63]:
df.to_csv('reddit-sentiment.csv', index=False)